artifact_uri: file:///c:/Users/user/Desktop/001 INTELLIGENCE ARTIFICIELLE EN INFORMATIQUE/Session
  4 Semestre 4 IA 2/Projet Capstone en IA/Projet_Capstone_IA/runs/mlflow/721280063832635170/a75882c89dae4d118710ccf1d13ad17b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '721280063832635170'
lifecycle_stage: active
run_id: a75882c89dae4d118710ccf1d13ad17b
run_name: Parking_Detection_Analysis
source_name: ''
source_type: 4
source_version: ''
start_time: 1776750232760
status: 1
tags: []
user_id: dongmo
