version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: alpr_backend
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./videos:/app/videos
      - ./mlflow.db:/app/mlflow.db
      # Persistance de la base SQLite native
      - ./parking.db:/app/parking.db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: alpr_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/api/v1/analyze/image
      - API_DB_URL=http://api:8000/api/v1/database/plates
    depends_on:
      - api
    restart: unless-stopped