artifact_location: file:///c:/Users/user/Desktop/001 INTELLIGENCE ARTIFICIELLE EN
  INFORMATIQUE/Session 4 Semestre 4 IA 2/Projet Capstone en IA/Projet_Capstone_IA/runs/mlflow/817468508864585305
creation_time: 1776747432047
experiment_id: '817468508864585305'
last_update_time: 1776747432047
lifecycle_stage: active
name: /Shared/Ultralytics
trace_location: null
workspace: default
