artifact_location: file:///c:/Users/user/Desktop/001 INTELLIGENCE ARTIFICIELLE EN
  INFORMATIQUE/Session 4 Semestre 4 IA 2/Projet Capstone en IA/Projet_Capstone_IA/runs/mlflow/721280063832635170
creation_time: 1776748636227
experiment_id: '721280063832635170'
last_update_time: 1776748636227
lifecycle_stage: active
name: Parking_Control_System
trace_location: null
workspace: default
