artifact_uri: file:///c:/Users/user/Desktop/001 INTELLIGENCE ARTIFICIELLE EN INFORMATIQUE/Session
  4 Semestre 4 IA 2/Projet Capstone en IA/Projet_Capstone_IA/runs/mlflow/721280063832635170/3b23688732b44e4784fbde2da37af6e4/artifacts
end_time: 1776750224787
entry_point_name: ''
experiment_id: '721280063832635170'
lifecycle_stage: active
run_id: 3b23688732b44e4784fbde2da37af6e4
run_name: Video_Final_Test
source_name: ''
source_type: 4
source_version: ''
start_time: 1776748902885
status: 3
tags: []
user_id: dongmo
