artifact_location: file:///c:/Users/user/Desktop/001 INTELLIGENCE ARTIFICIELLE EN
  INFORMATIQUE/Session 4 Semestre 4 IA 2/Projet Capstone en IA/Projet_Capstone_IA/runs/mlflow/836536265296596173
creation_time: 1776748854182
experiment_id: '836536265296596173'
last_update_time: 1776748854182
lifecycle_stage: active
name: Parking_Control_Video_Tests
trace_location: null
workspace: default
