artifact_uri: file:///c:/Users/user/Desktop/001 INTELLIGENCE ARTIFICIELLE EN INFORMATIQUE/Session
  4 Semestre 4 IA 2/Projet Capstone en IA/Projet_Capstone_IA/runs/mlflow/836536265296596173/158af7c1920e4ab498e82e9938d0090e/artifacts
end_time: 1776748888503
entry_point_name: ''
experiment_id: '836536265296596173'
lifecycle_stage: active
run_id: 158af7c1920e4ab498e82e9938d0090e
run_name: Video_Test_Sequence_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1776748854212
status: 3
tags: []
user_id: dongmo
