artifact_uri: file:///c:/Users/user/Desktop/001 INTELLIGENCE ARTIFICIELLE EN INFORMATIQUE/Session
  4 Semestre 4 IA 2/Projet Capstone en IA/Projet_Capstone_IA/runs/mlflow/721280063832635170/20089e2c894c4fcca7d838b0b721ef94/artifacts
end_time: 1776748839700
entry_point_name: ''
experiment_id: '721280063832635170'
lifecycle_stage: active
run_id: 20089e2c894c4fcca7d838b0b721ef94
run_name: Test_Detection_OCR_V1
source_name: ''
source_type: 4
source_version: ''
start_time: 1776748834591
status: 3
tags: []
user_id: dongmo
